### ISSUE TITLE
Website background fails to load

### ISSUE THREAD

**Issue by paoloambrosio-skyuk** [sky-uk/kfp-operator#141]
**Describe the bug**

The homepage doesn't display the theme's background.

![image](https://user-images.githubusercontent.com/13807361/178908513-5027f330-3f5e-4781-a4d5-b47adb44a5f7.png)

```css
#td-cover-block-0{background-image:url(/homepage-background_...)}
```

**To Reproduce**

For the result, just load the [homepage](https://sky-uk.github.io/kfp-operator/). For the cause, search for `url(/homepage-background` in the [index page](https://github.com/sky-uk/kfp-operator/blob/master/docs/index.html).

**Expected behavior**

![image](https://user-images.githubusercontent.com/13807361/178908315-b5faac7d-66d7-4732-83fe-7bad73955f67.png)

```css
#td-cover-block-0{background-image:url(https://sky-uk.github.io/kfp-operator/homepage-background_...)}
```

**Version and configuration**

v0.1.0

**Logs**

N/A

**Additional context**

It is a problem with the theme: https://github.com/google/docsy/issues/350
