### ISSUE TITLE
RunConfiguration Triggers

### ISSUE THREAD

**Issue by jmendesky** [sky-uk/kfp-operator#213]
## Overview 
`RunConfigurations` currently can only be trigger by Cron Schedules.

Extend the RC API to allow multiple trigger types as follows:

```yaml
apiVersion: pipelines.kubeflow.org/v1alpha4
kind: RunConfiguration
metadata:
  name: a-recurring-run
spec:
  pipeline: a-pipeline
  triggers:
  - type: schedule
    cronExpression: '0 0 * * * *'
  - type: runconfiguration
    name: another-run-configuration
```

## Tasks:
- Change apiVersion to `v1alpha5` replacing `schedule` with `triggers` where only type `cron` is allowed
- Introduce type `runconfiguration`

## Open questions:
- should multiple triggers of type cron be supported?
