### ISSUE TITLE
RunConfiguration pipeline change trigger

### ISSUE THREAD

**Issue by jmendesky** [sky-uk/kfp-operator#217]
## Overview

Trigger run configurations immediately when pipeline changes. This allows new versions to be tested without waiting for a schedule.

When a pipeline version is not fixed, pipeline changes currently result in the run configuration being updated to the new version. When this trigger is defined, it will also trigger a run. Nothing should happen when using a fixed pipeline version, unless the pipeline version changes in the run configuration itself.

## Design

It build on top of the redesigned trigger mechanism in #213.

```
apiVersion: pipelines.kubeflow.org/v1alpha5
kind: RunConfiguration
metadata:
  name: a-recurring-run
spec:
  run:
    pipeline: pipeline-without-version
    runtimeParameters:
    - name: foo
      value: bar
    experimentName: baz
  triggers:
  - type: change
```

- If the run references a dynamic pipeline version, trigger a run when the current pipeline version is different from `status.observedPipelineVersion`
- The run should be owned by the RC
