### ISSUE TITLE
Structured trigger format

### ISSUE THREAD

**Issue by paoloambrosio-skyuk** [sky-uk/kfp-operator#230]
## Overview

The design for #217 comes with two issues:
- Validation can get complicated as the number of triggers increases
- The CRD cannot express what fields are available for each trigger type

## Design

To solve these problems, we should use a technique similar to what [Argo Event TriggerTemplate](https://github.com/argoproj/argo-events/blob/master/api/sensor.md#triggertemplate) does.

```yaml
apiVersion: pipelines.kubeflow.org/v1alpha5
kind: RunConfiguration
metadata:
  name: ...
spec:
  run:
    ...
  triggers:
  - schedule:
      cronExpression: "1 2 3 4 5"
  - change: {}
```

Validation should be changed to allow only one trigger "type" (field).
