### ISSUE TITLE
Restructure RunConfiguration API

### ISSUE THREAD

**Issue by jmendesky** [sky-uk/kfp-operator#237]
RunConfigurations in the current format
```yaml
spec:
  triggers:
  - schedule:
       cronExpression: 1 2 3 4 5
   - schedule:
       cronExpression: 2 3 4 5 6
  - onChange: {}
```

have the following disadvantages:
- the syntax for `onChange` triggers is not intuitive
- several `onChange` triggers can be defined, which would not make sense
- the order of triggers is difficult to retain on roundtrips

a better structure is
```yaml
triggers
  schedules:
  - 1 2 3 4 5
  - 2 3 4 5 6
  onChange:
  - pipelines
```
