### ISSUE TITLE
Record latest run in RunConfiguration State

### ISSUE THREAD

**Issue by jmendesky** [sky-uk/kfp-operator#242]
Extend RunConfiguration CRD as follows:

```yaml
kind: RunConfiguration
spec: ...
status:
  latestRuns:
    succeeded:
      providerId: abc
```
Depends on https://github.com/sky-uk/kfp-operator/issues/248

Tasks:
- [ ] Add RunCompletion Event trigger that populates RC with the providerId
