### ISSUE TITLE
Trigger Run when dependency run finishes

### ISSUE THREAD

**Issue by jmendesky** [sky-uk/kfp-operator#243]
Extend RunConfiguration CRD as follows:
```yaml
kind: RunConfiguration
spec:
  triggers:
    runConfigurations:
    - dependendent-rc
status:
  dependencies:
    runConfigurations:
      dependent-rc:
        providerId: dependent-rc-456
  triggers:
    runConfigurations:
      dependent-rc:
        providerId: dependent-rc-123
```

Tasks:
- [x] change RC dependency watcher adding trigger dependencies (to enqueue reconciliation request when a trigger dependency RC finishes training)
- [x] `status.dependencies.dependent-rc.providerId` will have to be updated when `status.latestRuns.succeeded.providerId` of a dependency changes (also a trigger dependency, not only artifact)
- [x] trigger a run and update `status.triggers.dependent-rc.providerId` when different from `status.dependencies.dependent-rc.providerId`
