### ISSUE TITLE
v1beta1 - Drop status.SynchronizationState field

### ISSUE THREAD

**Issue by jmendesky** [sky-uk/kfp-operator#245]
Breaking changes that will require a version change to v1beta1:
- remove `status.SynchronizationState` as this is duplicated in `status.conditions.SynchronizationSucceeded` (work done in https://github.com/sky-uk/kfp-operator/issues/278)
   - need to check that the summary line can pick the status out of the conditions list, need to filter list on type: Synchronized and then output the reason attribute.
   - currently all checks are done on synchronizationState field so all uses will have to move
```
  conditions:
  - lastTransitionTime: "2024-09-12T09:07:11Z"
    message: ""
    observedGeneration: 1
    reason: **Succeeded**
    status: "True"
    type: **Synchronized**
```

Tasks:
- [x] Decommission `v1alpha2`-`v1alpha4` (include removing logic "For migration from v1alpha4", etc.)
- [ ] change all usages of status.SynchronizationState to use conditions entry
- [ ] version migration code needed
