### ISSUE TITLE
Populate RunConfiguration Artifacts from RunCompletionEvent

### ISSUE THREAD

**Issue by jmendesky** [sky-uk/kfp-operator#250]
Set Artifacts in RunConfiguration State as follows:

```yaml
kind: RunConfiguration
spec:
  run:
    ...
  triggers:
    ...
  artifacts:
  - name: an-artifact
     ...
status:
  latestRuns:
    succeeded:
      ...
      artifacts:
      - name: an-artifact
        location: gs://some/where
```

Depends on #246 and #249
