### ISSUE TITLE
Introduce Status Conditions

### ISSUE THREAD

**Issue by jmendesky** [sky-uk/kfp-operator#278]
[`status.conditions` fields](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#typical-status-properties) are used by k8s controllers to signal status updates to the user.

The KFP-Operator should introduce this for better debuggability and introduce the following fields

```
status:
  conditions:
  - lastTransitionTime: "2023-08-21T13:54:56Z"
    status: "True"
    type: SynchronizationSuccessfull
    message: "<Failure message if appliccable>"
    reason: "<SynchronizationState>"
    observedGeneration: 123
```

Open Questions:
- could `status.SynchronizationState` be removed?

Further Reading:
- https://maelvls.dev/kubernetes-conditions/
- https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#typical-status-properties
