### ISSUE TITLE
Pipeline versions cannot be run on VAI

### ISSUE THREAD

**Issue by jmendesky** [sky-uk/kfp-operator#287]
**Describe the bug**
Pipeline versions are persisted onto VAI runs as a label. Because VAI labels only support lowercase letters, numbers, dashes and underscores some valid pipeline versions result in VAI refusing the creation of the job.

**To Reproduce**
Create a Pipeline with a version containing dots, for example

```yaml
apiVersion: pipelines.kubeflow.org/v1alpha5
kind: Pipeline
metadata:
  annotations:
    pipelines.kubeflow.org/provider: vai
  name: kfp-operator-quickstart
spec:
  image: ghcr.io/kfp-operator/kfp-operator-quickstart:0.4.0
  tfxComponents: pipeline.create_components
```
