### ISSUE TITLE
Provide resource labels

### ISSUE THREAD

**Issue by jmendesky** [sky-uk/kfp-operator#300]
## Overview

It should be possible to configure resource labels that are passed onto resources created by the providers.

This would allow querying resources in the absence of predictable resource names.

## Open Questions

Should these labels be configurable in the resource's spec as below (1) or use the resource's metadata labels (2)?

```
apiVersion: pipelines.kubeflow.org/v1alpha5
kind: Pipeline
metadata:
  name: pipeline-sample
  labels:
    algorithm: penguin-classifier # Option 1
spec:
  ...
  labels:
    algorithm: penguin-classifier # Option 2
```
