### ISSUE TITLE
KFP Operator Webhook to implement Status Updater (Step 6)

### ISSUE THREAD

**Issue by grahamia** [sky-uk/kfp-operator#344]
## Overview

Currently an event source and sensor which triggers a workflow which uses the kfp-operator-status-updater docker image is used to update the status section of run/run-configuration resource.

example status section in run configuration (with an artifact):
```
status:
  latestRuns:
    succeeded:
      artifacts:
      - location: ...model_location...
        name: pushed_model
      providerId: my-vai-id
```

Operator can expose a webhook to provide the same feature. The provider sensor `{{ include "kfp-operator-provider.resource-prefix" $ }}-{{ $providerName }}-publish-events`, e.g. provider-vai-publish-events can have another trigger to call the webhook

### Current Architecture
![image](https://github.com/user-attachments/assets/bd484e2b-936b-4fe5-9788-1f2f408260e3)

### After Architecture
<img width="1259" alt="image" src="https://github.com/user-attachments/assets/f0d65230-8004-4858-8825-a6eb095e2464">
