### ISSUE TITLE
Provide debugging parameter to keep created workflows

### ISSUE THREAD

**Issue by jmendesky** [sky-uk/kfp-operator#37]
### Overview

By design, the operator deletes all workflows it creates on certain state transitions in order to keep the environments clean of unnecessary workloads. In certain situations, it would be useful to keep these workflows to allow debugging.

### Implementation notes

Add a configuration parameter to `Pipeline` and `RunConfiguration` resources which will define whether or not created workflows should be cleaned up:

```yaml
apiVersion: pipelines.kubeflow.org/v1
kind: Pipeline
metadata:
  name: pipeline-sample
  annotations:
    pipelines.kubeflow.org/debug: '{ "keepWorkflows": true }'
spec:
  ...
```

Add a debug section to the operator configuration to set global defaults.
```yaml
apiVersion: config.kubeflow.org/v1
kind: KfpControllerConfig
metadata:
  name: operatorconfig-sample
spec:
  debug: 
    keepWorkflows: true
```

All flags should be `or`-combined between the global defaults and resource configuration.

Propagate debug annotations onto created workflows to allow finding orphan workflows for manual cleanup and for making decisions.

### AC

 - [x] If the flag is set in the operator configuration, workflows should not be deleted
 - [x] If the flag is set in the resource, workflows created by that resource should not be deleted
 - [x] Workflows are deleted otherwise
 - [x] Docs are up to date
