### ISSUE TITLE
v1beta1 - Pipeline CRD - Make framework an object

### ISSUE THREAD

**Issue by grahamia** [sky-uk/kfp-operator#490]
## Description
add a new framework object and remove framework specific attributes from the root of the resource.
```
metadata:
  name: penguin-pipeline
spec:
  provider: kfp
  image: kfp-quickstart:v1
  framework:
    type: tfx
    parameters:
       components: pipeline.create_components
       beamArgs:
       - name: arg1
          value: value1
```
where framework is object with `tfx: string` and `parameters: map[string]*apiextensionsv1.JSON`

Root attributes which are TFX framework specific are tfcComponents and beamArgs, these should be move to the generic parameters section.

### Convert To (v1alpha# -> v1beta1)
- Check remainder annotation
- if empty
  - Assume must be tfx framework
  - move value from tfxComponents into parameters map.
  - move any beamArgs NameValue array from root into parameters map (can be empty)
- else
  - populate framework attribute

### Convert From
If type=tfx
- take value from parameters.components and put into tfxComponents
- take value from parameters.beamArgs and put into beamArgs
for any other type
- framework should be stored in a remainder annotation for later use in conversion back to v1beta1

### Other changes
- Pass new structure into workflow.
- TFX compiler change to lookup components from new location.
- update docs
