### ISSUE TITLE
Support fixed pipeline versions in RunConfiguration

### ISSUE THREAD

**Issue by jmendesky** [sky-uk/kfp-operator#67]
# Overview

For some rollout scenarios, it would be helpful to specify a fixed pipeline version in a `RunConfiguration` so that training can happen both for the latest version and that fixed version.

# Details

## The `RunConfiguration` CRD will be extended as follows:

```yaml
name: runconfiguration-sample
spec:
  pipelineName: pipeline-sample
```

to be changed to

```yaml
name: runconfiguration-sample
spec:
  pipeline: pipeline-sample:v12345-abcdef
```

## The published events will be changed as follows:

```json
{
  "status": "succeeded",
  "pipelineName": "pipeline-sample",
  "runConfigurationName": "runconfiguration-sample",
  "servingModelArtifacts": [
    {
      "name": "pipeline-sample:runconfiguration-samplenxj2r-1-3560699993:Pusher:pushed_model:0",
      "location": "gs://ml-dev-uswe2-mlops/pipeline-sample/Pusher/pushed_model/43793"
    }
  ]
}
```

`runConfigurationName` will only be set if the run was triggered from a reconfiguration - i.e. not as a one-off run.

# ACs

- [x] `RunConfiguration` CRD updated according to spec
- [x] If a pipeline version is specified, the runconfiguration will always trigger runs against this version
- [x] In all other cases, the runconfiguration will trigger runs against the latest available version of the pipeline
- [x] if a pipeline version is set, pipeline updates should not affect the RC
- [x] runConfiguration needs to be published as part of run completion events according to the spec
- [x] provide a use-case example in the docs
