### ISSUE TITLE
Emit Argo Events for failed training runs

### ISSUE THREAD

**Issue by jmendesky** [sky-uk/kfp-operator#75]
### Overview
Users of the KFP-Operator want to be informed when the training of a machine learning model has failed. This should be done similarly to how model-update events are triggered.

### Notes
- change existing event name for model updates from `model-update` to `run-completion`. This will be a breaking change
- events should look as follows:
```yaml
name: run-completion
payload:
  status: failed|succeeded
  pipelineName: <name of the pipeline>
  servingModelArtifact: []
```
