### ISSUE TITLE
Make Operator metrics available from Helm Chart

### ISSUE THREAD

**Issue by jmendesky** [sky-uk/kfp-operator#77]
### Overview

Kubebuilder emits a number of [metrics](https://book.kubebuilder.io/reference/metrics.html) that can be exposed via `ServiceMonitor`s. This should be made available and configurable in the Helm chart.

### Notes

- RBAC-based security should be configurable. If enabled, an rbac-proxy container will be started in the manager pod and the service monitor will point to this proxy. If disabled, the ServiceMonitor will point to the manager container directly
- Endpoint configuration should be configurable

Example configuration:

```yaml
manager:
  ...
  monitoring:
    create: true
    rbacSecured: true
    serviceManager:
      create: true
      endpointConfiguration:
        bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
        tlsConfig:
          insecureSkipVerify: true
```
